repos:
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-docstring-first
      - id: check-json
      - id: pretty-format-json
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        additional_dependencies: [tokenize-rt==3.2.0]
